(function(){
  const basePatch = window.patchNotesFrais;
  window.patchNotesFrais = function(html){
    html = basePatch ? basePatch(html) : html;
    if(window.NOTESFRAIS_CHANNEL !== 'mike') return html;
    if(html.includes('Mike English UI active')) return html;

    const pairs = [
      ['<html lang="fr">','<html lang="en">'],
      ['<title>NotesFrais â€” Mike</title>','<title>NotesFrais - Mike</title>'],
      ['<title>NotesFrais Ã¢â‚¬â€â€” Mike</title>','<title>NotesFrais - Mike</title>'],
      ['Chargement de NotesFrais...', 'Loading NotesFrais...'],
      ['Impossible de charger NotesFrais', 'Unable to load NotesFrais'],
      ['Connexion Ã  Supabaseâ€¦', 'Connecting to Supabase...'],
      ['Connexion ÃƒÂ  SupabaseÃ¢â‚¬Â¦', 'Connecting to Supabase...'],
      ['Chargement des frais de Mike', 'Loading Mike expenses'],
      ['NOTES DE FRAIS', 'EXPENSES'],
      ['Supabase connectÃ©', 'Supabase connected'],
      ['Supabase connectÃƒÂ©', 'Supabase connected'],
      ['Erreur connexion', 'Connection error'],
      ['PÃ‰RIODE', 'PERIOD'],
      ['PÃƒâ€°RIODE', 'PERIOD'],
      ['NAVIGATION', 'MENU'],
      ['Janvier 2026', 'January 2026'],
      ['FÃ©vrier 2026', 'February 2026'],
      ['FÃƒÂ©vrier 2026', 'February 2026'],
      ['Mars 2026', 'March 2026'],
      ['Avril 2026', 'April 2026'],
      ['Mai 2026', 'May 2026'],
      ['Juin 2026', 'June 2026'],
      ['Accueil', 'Home'],
      ['Historique', 'Expenses'],
      ['Statistiques', 'Stats'],
      ['RelevÃ© UBS', 'UBS statement'],
      ['RelevÃƒÂ© UBS', 'UBS statement'],
      ['Ajouter un frais', 'Add expense'],
      ['Import relevÃ© UBS', 'Import UBS statement'],
      ['Import relevÃƒÂ© UBS', 'Import UBS statement'],
      ['UBS chargÃ©', 'UBS loaded'],
      ['UBS chargÃƒÂ©', 'UBS loaded'],
      ['Tableau de bord des frais professionnels', 'Business expenses dashboard'],
      ['TOTAL', 'TOTAL'],
      ['TVA', 'VAT'],
      ['rÃ©cupÃ©rable', 'recoverable'],
      ['rÃƒÂ©cupÃƒÂ©rable', 'recoverable'],
      ['RÃ©conciliÃ©s', 'Matched'],
      ['RÃƒÂ©conciliÃƒÂ©s', 'Matched'],
      ['AprÃ¨s UBS', 'After UBS'],
      ['AprÃƒÂ¨s UBS', 'After UBS'],
      ['import fin de mois', 'month-end import'],
      ['OubliÃ©s', 'Missing'],
      ['OubliÃƒÂ©s', 'Missing'],
      ['Ã  rÃ©gulariser', 'to fix'],
      ['ÃƒÂ  rÃƒÂ©gulariser', 'to fix'],
      ['aucun âœ“', 'none âœ“'],
      ['RÃ‰CONCILIATION UBS', 'UBS MATCHING'],
      ['RÃƒâ€°CONCILIATION UBS', 'UBS MATCHING'],
      ['rÃ©conciliÃ©s', 'matched'],
      ['rÃƒÂ©conciliÃƒÂ©s', 'matched'],
      ['en attente', 'pending'],
      ['RÃ©partition par catÃ©gorie', 'Breakdown by category'],
      ['RÃƒÂ©partition par catÃƒÂ©gorie', 'Breakdown by category'],
      ['Soumettre les frais du mois', 'Submit monthly expenses'],
      ['Frais soumis !', 'Expenses submitted!'],
      ['RÃ©sumÃ© avant soumission', 'Review before submission'],
      ['RÃƒÂ©sumÃƒÂ© avant soumission', 'Review before submission'],
      ['DÃ©tail par catÃ©gorie', 'Category breakdown'],
      ['DÃƒÂ©tail par catÃƒÂ©gorie', 'Category breakdown'],
      ['Frais inclus', 'Included expenses'],
      ['Aucun frais sur ce mois.', 'No expenses for this month.'],
      ['Aucun frais Ã  soumettre.', 'No expenses to submit.'],
      ['Aucun frais ÃƒÂ  soumettre.', 'No expenses to submit.'],
      ['Retour', 'Back'],
      ['Confirmer la soumission', 'Confirm submission'],
      ['Frais soumis au service RH !', 'Expenses submitted to HR!'],
      ['Vue synthÃ©tique du mois', 'Monthly overview'],
      ['Vue synthetique du mois', 'Monthly overview'],
      ['Panier moyen', 'Average spend'],
      ['par dÃ©pense', 'per expense'],
      ['par depense', 'per expense'],
      ['Top commerÃ§ants', 'Top merchants'],
      ['Top commercants', 'Top merchants'],
      ['Tendance par mois', 'Monthly trend'],
      ['Aucune dÃ©pense sur cette pÃ©riode.', 'No expenses for this period.'],
      ['Aucune depense sur cette periode.', 'No expenses for this period.'],
      ['Vue dÃ©taillÃ©e Ã  venir', 'Detailed view coming soon'],
      ['Vue dÃƒÂ©taillÃƒÂ©e ÃƒÂ  venir', 'Detailed view coming soon'],
      ['frais', 'expenses'],
      ['avec justificatif', 'with receipt'],
      ['Rechercher un reÃ§u, montant, commerÃ§ant...', 'Search receipt, amount, merchant...'],
      ['Rechercher un reÃƒÂ§u, montant, commerÃƒÂ§ant...', 'Search receipt, amount, merchant...'],
      ['Tous', 'All'],
      ['Repas', 'Meals'],
      ['Transport', 'Transport'],
      ['HÃ´tel', 'Hotel'],
      ['HÃƒÂ´tel', 'Hotel'],
      ['MatÃ©riel', 'Equipment'],
      ['MatÃƒÂ©riel', 'Equipment'],
      ['Autre', 'Other'],
      ['Aucun frais pour ce mois', 'No expenses for this month'],
      ['Justificatif', 'Receipt'],
      ['Voir le justificatif', 'View receipt'],
      ['Voir', 'View'],
      ['Supprimer', 'Delete'],
      ['TÃ©lÃ©charger', 'Download'],
      ['TÃƒÂ©lÃƒÂ©charger', 'Download'],
      ['Ouvrir', 'Open'],
      ['Aucun justificatif', 'No receipt'],
      ['Rapprochement UBS', 'UBS matching'],
      ['RÃ©conciliation automatique', 'Automatic matching'],
      ['RÃƒÂ©conciliation automatique', 'Automatic matching'],
      ['Aucun relevÃ© UBS importÃ©', 'No UBS statement imported'],
      ['Aucun relevÃƒÂ© UBS importÃƒÂ©', 'No UBS statement imported'],
      ['Importez votre CSV UBS e-banking pour rÃ©concilier automatiquement', 'Import the UBS e-banking CSV for automatic matching'],
      ['Importez votre CSV UBS e-banking pour rÃƒÂ©concilier automatiquement', 'Import the UBS e-banking CSV for automatic matching'],
      ['Importer relevÃ© UBS', 'Import UBS statement'],
      ['Importer relevÃƒÂ© UBS', 'Import UBS statement'],
      ['DÃ©penses', 'Expenses'],
      ['DÃƒÂ©penses', 'Expenses'],
      ['Revenus', 'Income'],
      ['En attente', 'Pending'],
      ['Dans UBS â€” sans justificatif', 'In UBS - no receipt'],
      ['Dans UBS Ã¢â‚¬â€ sans justificatif', 'In UBS - no receipt'],
      ['Saisis â€” non trouvÃ©s dans UBS', 'Entered - not found in UBS'],
      ['Saisis Ã¢â‚¬â€ non trouvÃƒÂ©s dans UBS', 'Entered - not found in UBS'],
      ['CrÃ©er', 'Create'],
      ['CrÃƒÂ©er', 'Create'],
      ['Importer un nouveau relevÃ© UBS', 'Import a new UBS statement'],
      ['Importer un nouveau relevÃƒÂ© UBS', 'Import a new UBS statement'],
      ['Importer relevÃ© UBS', 'Import UBS statement'],
      ['Importer relevÃƒÂ© UBS', 'Import UBS statement'],
      ['Importer relevÃ© UBS', 'Import UBS statement'],
      ['Ajouter un frais', 'Add expense'],
      ['Justificatif â€” photo ou PDF', 'Receipt - photo or PDF'],
      ['Justificatif Ã¢â‚¬â€ photo ou PDF', 'Receipt - photo or PDF'],
      ['Glissez ou cliquez pour ajouter', 'Drop or tap to add'],
      ['Photo du ticket ou PDF', 'Receipt photo or PDF'],
      ['OCR en coursâ€¦', 'OCR scanning...'],
      ['OCR en coursÃ¢â‚¬Â¦', 'OCR scanning...'],
      ['OCR terminÃ© â€” donnÃ©es extraites automatiquement', 'OCR done - data extracted automatically'],
      ['OCR terminÃƒÂ© Ã¢â‚¬â€ donnÃƒÂ©es extraites automatiquement', 'OCR done - data extracted automatically'],
      ['OCR indisponible â€” saisissez manuellement', 'OCR unavailable - enter manually'],
      ['OCR indisponible Ã¢â‚¬â€ saisissez manuellement', 'OCR unavailable - enter manually'],
      ['stockÃ© dans Supabase', 'stored in Supabase'],
      ['stockÃƒÂ© dans Supabase', 'stored in Supabase'],
      ['CommerÃ§ant *', 'Merchant *'],
      ['CommerÃƒÂ§ant *', 'Merchant *'],
      ['Ex: Restaurant Le Bistrot', 'E.g. Restaurant Le Bistrot'],
      ['Montant CHF *', 'Amount CHF *'],
      ['Date', 'Date'],
      ['CatÃ©gorie', 'Category'],
      ['CatÃƒÂ©gorie', 'Category'],
      ['Note', 'Note'],
      ['Optionnelâ€¦', 'Optional...'],
      ['OptionnelÃ¢â‚¬Â¦', 'Optional...'],
      ['Annuler', 'Cancel'],
      ['Garder en brouillon', 'Save draft'],
      ['Confirmer', 'Confirm'],
      ['Upload en coursâ€¦', 'Uploading...'],
      ['Upload en coursÃ¢â‚¬Â¦', 'Uploading...'],
      ['Le commerÃ§ant est obligatoire', 'Merchant is required'],
      ['Le commerÃƒÂ§ant est obligatoire', 'Merchant is required'],
      ['Le montant est obligatoire', 'Amount is required'],
      ['Erreur upload:', 'Upload error:'],
      ['Frais enregistrÃ© !', 'Expense saved!'],
      ['Frais enregistrÃƒÂ© !', 'Expense saved!'],
      ['Frais gardÃ©', 'Expense saved'],
      ['Frais gardÃƒÂ©', 'Expense saved'],
      ['Tu peux scanner le suivant.', 'You can scan the next one.'],
      ['Scanner un autre', 'Scan another'],
      ['Scanner un reÃ§u', 'Scan receipt'],
      ['Scanner un recu', 'Scan receipt'],
      ['Mode terrain', 'Field mode'],
      ['Ajoute un frais en quelques secondes.', 'Add an expense in seconds.'],
      ['Salut Mike, on capture Ã§a vite.', 'Hi Mike, let\'s capture this quickly.'],
      ['Prends le reÃ§u, vÃ©rifie le montant, et câ€™est rangÃ© pour la finance.', 'Take the receipt, check the amount, and finance will have everything ready.'],
      ['Receipt â€” photo ou PDF', 'Receipt - photo or PDF'],
      ['Receipt Ã¢â‚¬â€ photo ou PDF', 'Receipt - photo or PDF'],
      ['Repartition par categorie', 'Breakdown by category'],
      ['Reconcilies', 'Matched'],
      ['recuperable', 'recoverable'],
      ['Code d\'accÃ¨s', 'Access code'],
      ['Code d\'accÃƒÂ¨s', 'Access code'],
      ['Entrez le code utilisateur ou finance pour ouvrir l\'application.', 'Enter the user or finance code to open the app.'],
      ['DÃ©verrouiller', 'Unlock'],
      ['DÃƒÂ©verrouiller', 'Unlock'],
      ['Code incorrect.', 'Incorrect code.'],
      ['AccÃ¨s protÃ©gÃ© par code local', 'Access protected by local code'],
      ['AccÃƒÂ¨s protÃƒÂ©gÃƒÂ© par code local', 'Access protected by local code'],
      ['Changer d\'accÃ¨s', 'Change access'],
      ['Changer d\'accÃƒÂ¨s', 'Change access'],
      ['frais en attente de synchronisation', 'expenses waiting to sync'],
      ['Ils sont gardÃ©s sur cet iPhone et partiront automatiquement dÃ¨s que la connexion revient.', 'They are saved on this iPhone and will sync automatically when the connection returns.'],
      ['Ils sont gardÃƒÂ©s sur cet iPhone et partiront automatiquement dÃƒÂ¨s que la connexion revient.', 'They are saved on this iPhone and will sync automatically when the connection returns.']
    ];

    for(const [from,to] of pairs){
      html = html.split(from).join(to);
    }
    html = html.replace('</body>', '<script>window.NOTESFRAIS_ENGLISH=true;console.info("Mike English UI active");<\/script></body>');
    return html;
  };
})();
