(function(){
  const basePatch = window.patchNotesFrais;
  window.patchNotesFrais = function(html){
    html = basePatch ? basePatch(html) : html;
    if(window.NOTESFRAIS_CHANNEL !== 'mike') return html;
    if(html.includes('Mike English UI active')) return html;

    const pairs = [
      ['<html lang="fr">','<html lang="en">'],
      ['<title>NotesFrais — Mike</title>','<title>NotesFrais - Mike</title>'],
      ['<title>NotesFrais â€”— Mike</title>','<title>NotesFrais - Mike</title>'],
      ['Chargement de NotesFrais...', 'Loading NotesFrais...'],
      ['Impossible de charger NotesFrais', 'Unable to load NotesFrais'],
      ['Connexion à Supabase…', 'Connecting to Supabase...'],
      ['Connexion Ã  Supabaseâ€¦', 'Connecting to Supabase...'],
      ['Chargement des frais de Mike', 'Loading Mike expenses'],
      ['NOTES DE FRAIS', 'EXPENSES'],
      ['Supabase connecté', 'Supabase connected'],
      ['Supabase connectÃ©', 'Supabase connected'],
      ['Erreur connexion', 'Connection error'],
      ['PÉRIODE', 'PERIOD'],
      ['PÃ‰RIODE', 'PERIOD'],
      ['NAVIGATION', 'MENU'],
      ['Janvier 2026', 'January 2026'],
      ['Février 2026', 'February 2026'],
      ['FÃ©vrier 2026', 'February 2026'],
      ['Mars 2026', 'March 2026'],
      ['Avril 2026', 'April 2026'],
      ['Mai 2026', 'May 2026'],
      ['Juin 2026', 'June 2026'],
      ['Accueil', 'Home'],
      ['Historique', 'Expenses'],
      ['Statistiques', 'Stats'],
      ['Relevé UBS', 'UBS statement'],
      ['RelevÃ© UBS', 'UBS statement'],
      ['Ajouter un frais', 'Add expense'],
      ['Import relevé UBS', 'Import UBS statement'],
      ['Import relevÃ© UBS', 'Import UBS statement'],
      ['UBS chargé', 'UBS loaded'],
      ['UBS chargÃ©', 'UBS loaded'],
      ['Tableau de bord des frais professionnels', 'Business expenses dashboard'],
      ['TOTAL', 'TOTAL'],
      ['TVA', 'VAT'],
      ['récupérable', 'recoverable'],
      ['rÃ©cupÃ©rable', 'recoverable'],
      ['Réconciliés', 'Matched'],
      ['RÃ©conciliÃ©s', 'Matched'],
      ['Après UBS', 'After UBS'],
      ['AprÃ¨s UBS', 'After UBS'],
      ['import fin de mois', 'month-end import'],
      ['Oubliés', 'Missing'],
      ['OubliÃ©s', 'Missing'],
      ['à régulariser', 'to fix'],
      ['Ã  rÃ©gulariser', 'to fix'],
      ['aucun ✓', 'none ✓'],
      ['RÉCONCILIATION UBS', 'UBS MATCHING'],
      ['RÃ‰CONCILIATION UBS', 'UBS MATCHING'],
      ['réconciliés', 'matched'],
      ['rÃ©conciliÃ©s', 'matched'],
      ['en attente', 'pending'],
      ['Répartition par catégorie', 'Breakdown by category'],
      ['RÃ©partition par catÃ©gorie', 'Breakdown by category'],
      ['Soumettre les frais du mois', 'Submit monthly expenses'],
      ['Frais soumis !', 'Expenses submitted!'],
      ['Résumé avant soumission', 'Review before submission'],
      ['RÃ©sumÃ© avant soumission', 'Review before submission'],
      ['Détail par catégorie', 'Category breakdown'],
      ['DÃ©tail par catÃ©gorie', 'Category breakdown'],
      ['Frais inclus', 'Included expenses'],
      ['Aucun frais sur ce mois.', 'No expenses for this month.'],
      ['Aucun frais à soumettre.', 'No expenses to submit.'],
      ['Aucun frais Ã  soumettre.', 'No expenses to submit.'],
      ['Retour', 'Back'],
      ['Confirmer la soumission', 'Confirm submission'],
      ['Frais soumis au service RH !', 'Expenses submitted to HR!'],
      ['Vue synthétique du mois', 'Monthly overview'],
      ['Vue synthetique du mois', 'Monthly overview'],
      ['Panier moyen', 'Average spend'],
      ['par dépense', 'per expense'],
      ['par depense', 'per expense'],
      ['Top commerçants', 'Top merchants'],
      ['Top commercants', 'Top merchants'],
      ['Tendance par mois', 'Monthly trend'],
      ['Aucune dépense sur cette période.', 'No expenses for this period.'],
      ['Aucune depense sur cette periode.', 'No expenses for this period.'],
      ['Vue détaillée à venir', 'Detailed view coming soon'],
      ['Vue dÃ©taillÃ©e Ã  venir', 'Detailed view coming soon'],
      ['frais', 'expenses'],
      ['avec justificatif', 'with receipt'],
      ['Rechercher un reçu, montant, commerçant...', 'Search receipt, amount, merchant...'],
      ['Rechercher un reÃ§u, montant, commerÃ§ant...', 'Search receipt, amount, merchant...'],
      ['Tous', 'All'],
      ['Repas', 'Meals'],
      ['Transport', 'Transport'],
      ['Hôtel', 'Hotel'],
      ['HÃ´tel', 'Hotel'],
      ['Matériel', 'Equipment'],
      ['MatÃ©riel', 'Equipment'],
      ['Autre', 'Other'],
      ['Aucun frais pour ce mois', 'No expenses for this month'],
      ['Justificatif', 'Receipt'],
      ['Voir le justificatif', 'View receipt'],
      ['Voir', 'View'],
      ['Supprimer', 'Delete'],
      ['Télécharger', 'Download'],
      ['TÃ©lÃ©charger', 'Download'],
      ['Ouvrir', 'Open'],
      ['Aucun justificatif', 'No receipt'],
      ['Rapprochement UBS', 'UBS matching'],
      ['Réconciliation automatique', 'Automatic matching'],
      ['RÃ©conciliation automatique', 'Automatic matching'],
      ['Aucun relevé UBS importé', 'No UBS statement imported'],
      ['Aucun relevÃ© UBS importÃ©', 'No UBS statement imported'],
      ['Importez votre CSV UBS e-banking pour réconcilier automatiquement', 'Import the UBS e-banking CSV for automatic matching'],
      ['Importez votre CSV UBS e-banking pour rÃ©concilier automatiquement', 'Import the UBS e-banking CSV for automatic matching'],
      ['Importer relevé UBS', 'Import UBS statement'],
      ['Importer relevÃ© UBS', 'Import UBS statement'],
      ['Dépenses', 'Expenses'],
      ['DÃ©penses', 'Expenses'],
      ['Revenus', 'Income'],
      ['En attente', 'Pending'],
      ['Dans UBS — sans justificatif', 'In UBS - no receipt'],
      ['Dans UBS â€” sans justificatif', 'In UBS - no receipt'],
      ['Saisis — non trouvés dans UBS', 'Entered - not found in UBS'],
      ['Saisis â€” non trouvÃ©s dans UBS', 'Entered - not found in UBS'],
      ['Créer', 'Create'],
      ['CrÃ©er', 'Create'],
      ['Importer un nouveau relevé UBS', 'Import a new UBS statement'],
      ['Importer un nouveau relevÃ© UBS', 'Import a new UBS statement'],
      ['Importer relevé UBS', 'Import UBS statement'],
      ['Importer relevÃ© UBS', 'Import UBS statement'],
      ['Importer relevé UBS', 'Import UBS statement'],
      ['Ajouter un frais', 'Add expense'],
      ['Justificatif — photo ou PDF', 'Receipt - photo or PDF'],
      ['Justificatif â€” photo ou PDF', 'Receipt - photo or PDF'],
      ['Glissez ou cliquez pour ajouter', 'Drop or tap to add'],
      ['Photo du ticket ou PDF', 'Receipt photo or PDF'],
      ['OCR en cours…', 'OCR scanning...'],
      ['OCR en coursâ€¦', 'OCR scanning...'],
      ['OCR terminé — données extraites automatiquement', 'OCR done - data extracted automatically'],
      ['OCR terminÃ© â€” donnÃ©es extraites automatiquement', 'OCR done - data extracted automatically'],
      ['OCR indisponible — saisissez manuellement', 'OCR unavailable - enter manually'],
      ['OCR indisponible â€” saisissez manuellement', 'OCR unavailable - enter manually'],
      ['stocké dans Supabase', 'stored in Supabase'],
      ['stockÃ© dans Supabase', 'stored in Supabase'],
      ['Commerçant *', 'Merchant *'],
      ['CommerÃ§ant *', 'Merchant *'],
      ['Ex: Restaurant Le Bistrot', 'E.g. Restaurant Le Bistrot'],
      ['Montant CHF *', 'Amount CHF *'],
      ['Date', 'Date'],
      ['Catégorie', 'Category'],
      ['CatÃ©gorie', 'Category'],
      ['Note', 'Note'],
      ['Optionnel…', 'Optional...'],
      ['Optionnelâ€¦', 'Optional...'],
      ['Annuler', 'Cancel'],
      ['Garder en brouillon', 'Save draft'],
      ['Confirmer', 'Confirm'],
      ['Upload en cours…', 'Uploading...'],
      ['Upload en coursâ€¦', 'Uploading...'],
      ['Le commerçant est obligatoire', 'Merchant is required'],
      ['Le commerÃ§ant est obligatoire', 'Merchant is required'],
      ['Le montant est obligatoire', 'Amount is required'],
      ['Erreur upload:', 'Upload error:'],
      ['Frais enregistré !', 'Expense saved!'],
      ['Frais enregistrÃ© !', 'Expense saved!'],
      ['Frais gardé', 'Expense saved'],
      ['Frais gardÃ©', 'Expense saved'],
      ['Tu peux scanner le suivant.', 'You can scan the next one.'],
      ['Scanner un autre', 'Scan another'],
      ['Scanner un reçu', 'Scan receipt'],
      ['Scanner un recu', 'Scan receipt'],
      ['Mode terrain', 'Field mode'],
      ['Ajoute un frais en quelques secondes.', 'Add an expense in seconds.'],
      ['Code d\'accès', 'Access code'],
      ['Code d\'accÃ¨s', 'Access code'],
      ['Entrez le code utilisateur ou finance pour ouvrir l\'application.', 'Enter the user or finance code to open the app.'],
      ['Déverrouiller', 'Unlock'],
      ['DÃ©verrouiller', 'Unlock'],
      ['Code incorrect.', 'Incorrect code.'],
      ['Accès protégé par code local', 'Access protected by local code'],
      ['AccÃ¨s protÃ©gÃ© par code local', 'Access protected by local code'],
      ['Changer d\'accès', 'Change access'],
      ['Changer d\'accÃ¨s', 'Change access'],
      ['frais en attente de synchronisation', 'expenses waiting to sync'],
      ['Ils sont gardés sur cet iPhone et partiront automatiquement dès que la connexion revient.', 'They are saved on this iPhone and will sync automatically when the connection returns.'],
      ['Ils sont gardÃ©s sur cet iPhone et partiront automatiquement dÃ¨s que la connexion revient.', 'They are saved on this iPhone and will sync automatically when the connection returns.']
    ];

    for(const [from,to] of pairs){
      html = html.split(from).join(to);
    }
    html = html.replace('</body>', '<script>window.NOTESFRAIS_ENGLISH=true;console.info("Mike English UI active");<\/script></body>');
    return html;
  };
})();
